name: Deploy API

on:
  push:
    branches:
      - main
    paths: 
      - "apps/api/**"
      - "packages/**"
      - "!apps/web/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: appleboy/ssh-action@v1.2.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          set -e

          export NVM_DIR="/root/.nvm"
          export PATH="$NVM_DIR/versions/node/v24.18.0/bin:/root/.local/share/pnpm/bin:$PATH"
         
          cd /opt/next-saas-rbac/
  
          git pull origin main

          pnpm --filter api install --frozen-lockfile
          pnpm --filter api prisma migrate deploy
          pnpm --filter api prisma generate
          pnpm --filter api run build
          
          systemctl restart next-saas-api
          systemctl restart nginx
